name: icondo
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  dio: ^5.8.0+1

  json_annotation: ^4.9.0
  retrofit: ^4.1.0
  flutter_svg: ^2.0.7
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output_dir: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
    lottie: false

  class_name: Assets
  package_name: null
  constant_name: null
  path_constraints:
    - assets/images/
